### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by XayOn** [XayOn/torrentstream#2]
Nobody is using this, yet it's still a good code example of a torrent streaming service.

**Comment by pataquets** [comment]
I've stumbled upon this and ended with no clue if it might work for me. At least the description made me browse the project page. A short description and have example of screenshot might be enough to spark curiosity in order to people to try it.

In case you were wondering if it has to do anything with software features of quality :) .
Thanks for sharing, anyway.

**Comment by XayOn** [comment]
@pataquets  It's a torrenting library, maybe a code example would help, but clearly not a screenshot. 
It's not anything with a user interface. If you're looking for code examples on how to work directly with libtorrent from within python, add trackers, set sequential mode on torrents and launch an external application to stream them with asyncio, then yes, you can use this 😃 

I'll add documentation, update the readme and probably mark it as deprecated anyway as I don't have much time to mantain this and I've got a few more projects (you can have a look at them at my profile) that require attention currently. Basically, recover what I already had here ( https://python-simpletorrentstreaming.readthedocs.io/en/latest/readme.html#usage ) that I lost for some reason (it's been a while! This project has been out of maintenance for five years!) 

This project will be open for mantainers, and I'll still be able to merge pull requests, etc if it comes to that, but there are a lot of good torrenting streaming applications right now

**Comment by XayOn** [comment]
@pataquets Closing this, I added a readme, a CLI util and restructured the whole project, with poetry, async generators and context managers.
